### ISSUE TITLE
help Louis find "in preparation" orders

### ISSUE THREAD

**Issue by Aimerico** [Dahan13/spatulas#32]
Quand louis nous envoie 25 commandes en cuisines réparties sur différents créneaux et qu'ensuite ils ne retrouve plus celles qu'il a envoyé pour les valider une fois qu'on lui amène ces 25 burgers....

**Comment by BebertDeChast** [comment]
on va changer l affichage caisse pour simplifier le parcours entre les différentes commandes 
ca vaut peut etre le coup de mettre en place des filtres activables
